#!/usr/bin/env bash

if [ $# -ne 2 ];then
   echo "Invalid number of parameters.  Usage: fault.sh <event type> <message code>"
   exit 1
fi

case "$1" in
        c)
            type="critical"
            ;;
        a)
            type="abnormal"
            ;;

        e)
            type="event"
            ;;
        h)
            type="health"
            ;;
        *)
            echo $"Usage: $0 { c - critical | a - abnormal | e - event | h - health }"
            exit 1
esac

cmd="faulttool -T $type -t HW -c $2 -- Hardware $type event."
echo $cmd
`$cmd`
