#! /bin/bash

function print_key_value() {
    val=`cat $1 | jq ".[]| .${2}"`
    printf "  \"%s\": %s\n" "$2" "$val" >> ${logger}
}

tstamp=`date +%m-%d_%H:%M:%S`
logger="gwsdiagnostics.${tstamp}.log"
printf "Diagnosing at %s\n" "`date`" > ${logger}
printf "TESTSTEP: %s\n" "$1" >> ${logger}

printf "Contents of /var/jaguar/bsg:\n" >> ${logger}
bsg_profiles=(/var/jaguar/bsg/lru*)
for profile in "${bsg_profiles[@]}"; do
   printf "%s\n" "`ls -l ${profile}`" >> ${logger}
   print_key_value ${profile} "service.gws.active"
   print_key_value ${profile} "service.gws.partnerID"
   print_key_value ${profile} "service.gws.auth_url"
   printf "\n" >> ${logger}
done

jctl_cmd='journalctl -u ground-service --since "10 minutes ago"'
printf "%s\n" "$jctl_cmd" >> ${logger}
journalctl -u ground-service --since "10 minutes ago" >> ${logger}
